/* ══════════════════════════════════════════════════════
   Create a new child profile linked to the authenticated parent.
   Uses service role key to bypass RLS.

   POST  Authorization: Bearer <supabase_jwt>
   Body: { name: string, year_group: 'P6' | 'P7' }
   Returns: { ok: true, childId, name } or { ok: false, error }
══════════════════════════════════════════════════════ */
export const config = { maxDuration: 10 };

const SUPABASE_URL = 'https://iutcgogmxhaqgaxkznxu.supabase.co';

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ ok: false, error: 'Method not allowed' });

  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!serviceKey) return res.status(500).json({ ok: false, error: 'Server misconfigured' });

  // 1. Verify the caller is an authenticated parent
  const jwt = (req.headers.authorization || '').replace(/^Bearer\s+/i, '');
  if (!jwt) return res.status(401).json({ ok: false, error: 'Missing Authorization header' });

  const userRes = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
    headers: { 'apikey': serviceKey, 'Authorization': `Bearer ${jwt}` },
  });
  if (!userRes.ok) return res.status(401).json({ ok: false, error: 'Invalid or expired session' });
  const { id: parentId } = await userRes.json();

  // 2. Validate inputs
  const { name, year_group } = req.body || {};
  const trimmedName = (name || '').trim().slice(0, 64);
  if (!trimmedName) return res.status(400).json({ ok: false, error: 'Name is required' });
  if (!['P6', 'P7'].includes(year_group)) {
    return res.status(400).json({ ok: false, error: 'year_group must be P6 or P7' });
  }

  // 3. Insert new child profile row (id auto-generated by Supabase)
  const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/profiles`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': serviceKey,
      'Authorization': `Bearer ${serviceKey}`,
      'Prefer': 'return=representation',
    },
    body: JSON.stringify({
      parent_id:           parentId,
      name:                trimmedName,
      year_group,
      onboarded:           true,
      subscription_status: 'inactive',
      free_sprints_used:   0,
      updated_at:          new Date().toISOString(),
    }),
  });

  if (!insertRes.ok) {
    const text = await insertRes.text();
    console.error('[add-child] insert error:', insertRes.status, text.slice(0, 300));
    return res.status(500).json({ ok: false, error: 'Failed to create child profile' });
  }

  const [child] = await insertRes.json();
  console.log(`[add-child] ✅ child ${child.id} created for parent ${parentId}`);
  return res.status(200).json({ ok: true, childId: child.id, name: child.name });
}
